import type { PlanetData, Spacecraft } from '$lib/types';

// Real orbital elements (J2000 epoch) with display scaling
// Display: 1 AU = 50 scene units, planet sizes are exaggerated for visibility
const AU = 50; // scene units per AU
const EPOCH_J2000 = 2451545.0;

export const SUN_DATA = {
	name: 'Sun',
	radius: 8, // scene units
	realRadius: 696340, // km
	color: 0xfff5dd,
};

export const PLANETS: PlanetData[] = [
	{
		name: 'Mercury',
		radius: 0.8,
		realRadius: 2439.7,
		semiMajorAxis: 0.387 * AU,
		realSemiMajorAxis: 0.387,
		eccentricity: 0.2056,
		inclination: 7.005,
		longitudeAscendingNode: 48.331,
		argumentPerihelion: 29.124,
		meanAnomalyAtEpoch: 174.796,
		epoch: EPOCH_J2000,
		orbitalPeriod: 87.969,
		color: 0x8c7853,
		rotationSpeed: 0.0007,
	},
	{
		name: 'Venus',
		radius: 1.5,
		realRadius: 6051.8,
		semiMajorAxis: 0.723 * AU,
		realSemiMajorAxis: 0.723,
		eccentricity: 0.0068,
		inclination: 3.395,
		longitudeAscendingNode: 76.680,
		argumentPerihelion: 54.884,
		meanAnomalyAtEpoch: 50.115,
		epoch: EPOCH_J2000,
		orbitalPeriod: 224.701,
		color: 0xe8b873,
		rotationSpeed: -0.0002,
		hasAtmosphere: true,
		atmosphereColor: 0xe8c878,
	},
	{
		name: 'Earth',
		radius: 1.6,
		realRadius: 6371.0,
		semiMajorAxis: 1.0 * AU,
		realSemiMajorAxis: 1.0,
		eccentricity: 0.0167,
		inclination: 0.000,
		longitudeAscendingNode: -11.260,
		argumentPerihelion: 114.208,
		meanAnomalyAtEpoch: 358.617,
		epoch: EPOCH_J2000,
		orbitalPeriod: 365.256,
		color: 0x4a90d9,
		rotationSpeed: 0.04,
		hasAtmosphere: true,
		atmosphereColor: 0x4488ff,
	},
	{
		name: 'Mars',
		radius: 1.1,
		realRadius: 3389.5,
		semiMajorAxis: 1.524 * AU,
		realSemiMajorAxis: 1.524,
		eccentricity: 0.0934,
		inclination: 1.850,
		longitudeAscendingNode: 49.558,
		argumentPerihelion: 286.502,
		meanAnomalyAtEpoch: 19.412,
		epoch: EPOCH_J2000,
		orbitalPeriod: 686.980,
		color: 0xc1440e,
		rotationSpeed: 0.039,
	},
	{
		name: 'Jupiter',
		radius: 4.0,
		realRadius: 69911,
		semiMajorAxis: 5.203 * AU,
		realSemiMajorAxis: 5.203,
		eccentricity: 0.0489,
		inclination: 1.303,
		longitudeAscendingNode: 100.464,
		argumentPerihelion: 273.867,
		meanAnomalyAtEpoch: 20.020,
		epoch: EPOCH_J2000,
		orbitalPeriod: 4332.589,
		color: 0xd8a878,
		rotationSpeed: 0.095,
		hasAtmosphere: true,
		atmosphereColor: 0xd4a878,
	},
	{
		name: 'Saturn',
		radius: 3.5,
		realRadius: 58232,
		semiMajorAxis: 9.537 * AU,
		realSemiMajorAxis: 9.537,
		eccentricity: 0.0539,
		inclination: 2.485,
		longitudeAscendingNode: 113.665,
		argumentPerihelion: 339.392,
		meanAnomalyAtEpoch: 317.020,
		epoch: EPOCH_J2000,
		orbitalPeriod: 10759.22,
		color: 0xe0c896,
		rotationSpeed: 0.088,
		hasAtmosphere: true,
		atmosphereColor: 0xe0c896,
		rings: { inner: 4.5, outer: 7.5, color: 0xc4a878 },
	},
	{
		name: 'Uranus',
		radius: 2.5,
		realRadius: 25362,
		semiMajorAxis: 19.191 * AU,
		realSemiMajorAxis: 19.191,
		eccentricity: 0.0473,
		inclination: 0.773,
		longitudeAscendingNode: 74.006,
		argumentPerihelion: 96.998,
		meanAnomalyAtEpoch: 142.238,
		epoch: EPOCH_J2000,
		orbitalPeriod: 30688.5,
		color: 0x8ec5d1,
		rotationSpeed: -0.055,
		hasAtmosphere: true,
		atmosphereColor: 0x8ec5d1,
	},
	{
		name: 'Neptune',
		radius: 2.4,
		realRadius: 24622,
		semiMajorAxis: 30.069 * AU,
		realSemiMajorAxis: 30.069,
		eccentricity: 0.0086,
		inclination: 1.770,
		longitudeAscendingNode: 131.784,
		argumentPerihelion: 276.336,
		meanAnomalyAtEpoch: 256.228,
		epoch: EPOCH_J2000,
		orbitalPeriod: 60182,
		color: 0x3b5fc9,
		rotationSpeed: 0.058,
		hasAtmosphere: true,
		atmosphereColor: 0x3b5fc9,
	},
];

export const MOON_DATA = {
	name: 'Moon',
	radius: 0.4,
	semiMajorAxis: 3.5, // scene units from Earth
	eccentricity: 0.0549,
	inclination: 5.145,
	longitudeAscendingNode: 0,
	argumentPerihelion: 0,
	meanAnomalyAtEpoch: 135.27,
	epoch: EPOCH_J2000,
	orbitalPeriod: 27.322, // days
	color: 0xcccccc,
};

// Notable comets and asteroids for default display (fallback if API fails)
// NASA JPL tracks ~1.3 million small bodies - these are curated defaults
export const NOTABLE_OBJECTS = [
	// Famous periodic comets
	{ des: '1P', name: 'Halley', kind: 'comet' as const },
	{ des: '2P', name: 'Encke', kind: 'comet' as const },
	{ des: '4P', name: 'Faye', kind: 'comet' as const },
	{ des: '6P', name: "d'Arrest", kind: 'comet' as const },
	{ des: '7P', name: 'Pons-Winnecke', kind: 'comet' as const },
	{ des: '8P', name: 'Tuttle', kind: 'comet' as const },
	{ des: '9P', name: 'Tempel 1', kind: 'comet' as const },
	{ des: '10P', name: 'Tempel', kind: 'comet' as const },
	{ des: '15P', name: 'Finlay', kind: 'comet' as const },
	{ des: '17P', name: 'Holmes', kind: 'comet' as const },
	{ des: '19P', name: 'Borrelly', kind: 'comet' as const },
	{ des: '21P', name: 'Giacobini-Zinner', kind: 'comet' as const },
	{ des: '22P', name: 'Kopff', kind: 'comet' as const },
	{ des: '23P', name: 'Brorsen-Metcalf', kind: 'comet' as const },
	{ des: '24P', name: 'Schaumasse', kind: 'comet' as const },
	{ des: '28P', name: 'Neujmin 1', kind: 'comet' as const },
	{ des: '29P', name: 'Schwassmann-Wachmann', kind: 'comet' as const },
	{ des: '41P', name: 'Tuttle-Giacobini-Kresak', kind: 'comet' as const },
	{ des: '45P', name: 'Honda-Mrkos-Pajdusakova', kind: 'comet' as const },
	{ des: '46P', name: 'Wirtanen', kind: 'comet' as const },
	{ des: '48P', name: 'Johnson', kind: 'comet' as const },
	{ des: '49P', name: 'Arend-Rigaux', kind: 'comet' as const },
	{ des: '55P', name: 'Tempel-Tuttle', kind: 'comet' as const },
	{ des: '62P', name: 'Tsuchinshan', kind: 'comet' as const },
	{ des: '67P', name: 'Churyumov-Gerasimenko', kind: 'comet' as const },
	{ des: '73P', name: 'Schwassmann-Wachmann 3', kind: 'comet' as const },
	{ des: '78P', name: 'Gehrels', kind: 'comet' as const },
	{ des: '81P', name: 'Wild 2', kind: 'comet' as const },
	{ des: '88P', name: 'Howell', kind: 'comet' as const },
	{ des: '103P', name: 'Hartley 2', kind: 'comet' as const },
	{ des: '144P', name: 'Swift', kind: 'comet' as const },
	{ des: '157P', name: 'Tritton', kind: 'comet' as const },
	{ des: '169P', name: 'NEAT', kind: 'comet' as const },
	{ des: '185P', name: 'Petriew', kind: 'comet' as const },
	{ des: '210P', name: 'Christensen', kind: 'comet' as const },
	{ des: '215P', name: 'NEAT', kind: 'comet' as const },
	{ des: '220P', name: 'McNaught', kind: 'comet' as const },
	{ des: '226P', name: 'Pigott-LINEAR-Kowalski', kind: 'comet' as const },
	{ des: '228P', name: 'LINEAR', kind: 'comet' as const },
	{ des: '235P', name: 'LINEAR', kind: 'comet' as const },
	{ des: '260P', name: 'McNaught', kind: 'comet' as const },
	{ des: '289P', name: 'Bouvier', kind: 'comet' as const },
	{ des: '290P', name: 'Jager', kind: 'comet' as const },
	{ des: '300P', name: 'Catalina', kind: 'comet' as const },
	// Notable long-period comets
	{ des: 'C/2023 A3', name: 'Tsuchinshan-ATLAS', kind: 'comet' as const },
	{ des: 'C/2024 G3', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2023 R1', name: 'PANSTARRS', kind: 'comet' as const },
	{ des: 'C/2024 J3', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2024 T5', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2024 R4', name: 'PANSTARRS', kind: 'comet' as const },
	{ des: 'C/2025 M2', name: 'PANSTARRS', kind: 'comet' as const },
	{ des: 'C/2025 Y1', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2022 QE78', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2021 G2', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2014 UN271', name: 'Bernardinelli-Bernstein', kind: 'comet' as const },
	// Famous historical long-period comets
	{ des: 'C/1995 O1', name: 'Hale-Bopp', kind: 'comet' as const },
	{ des: 'C/1996 B2', name: 'Hyakutake', kind: 'comet' as const },
	{ des: 'C/2006 P1', name: 'McNaught', kind: 'comet' as const },
	{ des: 'C/2020 F3', name: 'NEOWISE', kind: 'comet' as const },
	{ des: 'C/2011 L4', name: 'PANSTARRS', kind: 'comet' as const },
	{ des: 'C/2020 K1', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2019 Y4', name: 'ATLAS', kind: 'comet' as const },
	{ des: 'C/2021 A1', name: 'Leonard', kind: 'comet' as const },
	// Centaurs
	{ des: '2060', name: 'Chiron', kind: 'asteroid' as const },
	{ des: '5145', name: 'Pholus', kind: 'asteroid' as const },
	{ des: '7066', name: 'Nessus', kind: 'asteroid' as const },
	{ des: '8405', name: 'Asbolus', kind: 'asteroid' as const },
	{ des: '10199', name: 'Chariklo', kind: 'asteroid' as const },
	// Trans-Neptunian objects (TNOs)
	{ des: '136199', name: 'Eris', kind: 'asteroid' as const },
	{ des: '136472', name: 'Makemake', kind: 'asteroid' as const },
	{ des: '90482', name: 'Orcus', kind: 'asteroid' as const },
	{ des: '50000', name: 'Quaoar', kind: 'asteroid' as const },
	{ des: '90377', name: 'Sedna', kind: 'asteroid' as const },
	{ des: '225088', name: 'Gonggong', kind: 'asteroid' as const },
	{ des: '202421', name: '2014 UZ224', kind: 'asteroid' as const },
	// Additional notable asteroids
	{ des: '21', name: 'Lutetia', kind: 'asteroid' as const },
	{ des: '243', name: 'Ida', kind: 'asteroid' as const },
	{ des: '951', name: 'Gaspra', kind: 'asteroid' as const },
	{ des: '9969', name: 'Braille', kind: 'asteroid' as const },
	{ des: '253', name: 'Mathilde', kind: 'asteroid' as const },
	{ des: '5535', name: 'Annefrank', kind: 'asteroid' as const },
	{ des: '9942', name: '1990 UO', kind: 'asteroid' as const },
	// Main belt asteroids (largest/most notable)
	{ des: '1', name: 'Ceres', kind: 'asteroid' as const },
	{ des: '2', name: 'Pallas', kind: 'asteroid' as const },
	{ des: '3', name: 'Juno', kind: 'asteroid' as const },
	{ des: '4', name: 'Vesta', kind: 'asteroid' as const },
	{ des: '5', name: 'Astraea', kind: 'asteroid' as const },
	{ des: '6', name: 'Hebe', kind: 'asteroid' as const },
	{ des: '7', name: 'Iris', kind: 'asteroid' as const },
	{ des: '8', name: 'Flora', kind: 'asteroid' as const },
	{ des: '9', name: 'Metis', kind: 'asteroid' as const },
	{ des: '10', name: 'Hygiea', kind: 'asteroid' as const },
	{ des: '15', name: 'Eunomia', kind: 'asteroid' as const },
	{ des: '16', name: 'Psyche', kind: 'asteroid' as const },
	{ des: '52', name: 'Europa', kind: 'asteroid' as const },
	{ des: '65', name: 'Cybele', kind: 'asteroid' as const },
	{ des: '87', name: 'Sylvia', kind: 'asteroid' as const },
	{ des: '88', name: 'Thisbe', kind: 'asteroid' as const },
	{ des: '311', name: 'Claudia', kind: 'asteroid' as const },
	{ des: '511', name: 'Davida', kind: 'asteroid' as const },
	{ des: '704', name: 'Interamnia', kind: 'asteroid' as const },
	// Near-Earth asteroids (NEAs)
	{ des: '433', name: 'Eros', kind: 'asteroid' as const },
	{ des: '719', name: 'Albert', kind: 'asteroid' as const },
	{ des: '887', name: 'Alinda', kind: 'asteroid' as const },
	{ des: '1036', name: 'Ganymed', kind: 'asteroid' as const },
	{ des: '1566', name: 'Icarus', kind: 'asteroid' as const },
	{ des: '1620', name: 'Geographos', kind: 'asteroid' as const },
	{ des: '1862', name: 'Apollo', kind: 'asteroid' as const },
	{ des: '1865', name: 'Cerberus', kind: 'asteroid' as const },
	{ des: '1981', name: 'Midas', kind: 'asteroid' as const },
	{ des: '2063', name: 'Bacchus', kind: 'asteroid' as const },
	{ des: '2100', name: 'Ra-Shalom', kind: 'asteroid' as const },
	{ des: '2101', name: 'Adonis', kind: 'asteroid' as const },
	{ des: '2201', name: 'Oljato', kind: 'asteroid' as const },
	{ des: '3200', name: 'Phaethon', kind: 'asteroid' as const },
	{ des: '3361', name: 'Orpheus', kind: 'asteroid' as const },
	{ des: '3362', name: 'Khufu', kind: 'asteroid' as const },
	{ des: '3552', name: "Don Quixote", kind: 'asteroid' as const },
	{ des: '3671', name: 'Dionysus', kind: 'asteroid' as const },
	{ des: '4015', name: 'Wilson-Harrington', kind: 'asteroid' as const },
	{ des: '4179', name: 'Toutatis', kind: 'asteroid' as const },
	{ des: '4183', name: 'Cuno', kind: 'asteroid' as const },
	{ des: '4341', name: 'Poseidon', kind: 'asteroid' as const },
	{ des: '4450', name: 'Pan', kind: 'asteroid' as const },
	{ des: '4486', name: 'Mithra', kind: 'asteroid' as const },
	{ des: '5143', name: 'Hera', kind: 'asteroid' as const },
	{ des: '5189', name: '1990 UQ', kind: 'asteroid' as const },
	{ des: '5381', name: 'Sekhmet', kind: 'asteroid' as const },
	{ des: '5587', name: '1990 SB', kind: 'asteroid' as const },
	{ des: '6063', name: 'Jason', kind: 'asteroid' as const },
	{ des: '6489', name: 'Golevka', kind: 'asteroid' as const },
	{ des: '7092', name: 'Cadmus', kind: 'asteroid' as const },
	{ des: '8567', name: '1996 HW1', kind: 'asteroid' as const },
	{ des: '25143', name: 'Itokawa', kind: 'asteroid' as const },
	{ des: '99942', name: 'Apophis', kind: 'asteroid' as const },
	{ des: '101955', name: 'Bennu', kind: 'asteroid' as const },
	{ des: '162173', name: 'Ryugu', kind: 'asteroid' as const },
	{ des: '65803', name: 'Didymos', kind: 'asteroid' as const },
	{ des: '26701', name: '2001 FJ85', kind: 'asteroid' as const },
	// Potentially hazardous asteroids (PHAs)
	{ des: '29075', name: '1950 DA', kind: 'asteroid' as const },
	{ des: '8666', name: '1990 SZ', kind: 'asteroid' as const },
	{ des: '152564', name: '1992 RB', kind: 'asteroid' as const },
	{ des: '153814', name: '2001 WN5', kind: 'asteroid' as const },
	{ des: '161989', name: 'Cacus', kind: 'asteroid' as const },
	{ des: '68950', name: '2002 QF15', kind: 'asteroid' as const },
];

// Interstellar and deep space missions
// NAIF IDs are negative for spacecraft in JPL Horizons
export const INTERSTELLAR_MISSIONS: Spacecraft[] = [
	{
		id: 'voyager1',
		name: 'Voyager 1',
		naifId: -31,
		launchDate: '1977-09-05',
		color: 0x44aaff,
		description: 'Farthest human-made object, entered interstellar space in 2012',
		status: 'active',
	},
	{
		id: 'voyager2',
		name: 'Voyager 2',
		naifId: -32,
		launchDate: '1977-08-20',
		color: 0x44ffaa,
		description: 'Only spacecraft to visit all four giant planets, entered interstellar space in 2018',
		status: 'active',
	},
	{
		id: 'pioneer10',
		name: 'Pioneer 10',
		naifId: -23,
		launchDate: '1972-03-03',
		color: 0xffaa44,
		description: 'First spacecraft to cross the asteroid belt and visit Jupiter, last signal 2003',
		status: 'silent',
	},
	{
		id: 'pioneer11',
		name: 'Pioneer 11',
		naifId: -24,
		launchDate: '1973-04-06',
		color: 0xff8844,
		description: 'First to visit Saturn and fly through the rings, last signal 1995',
		status: 'silent',
	},
	{
		id: 'newhorizons',
		name: 'New Horizons',
		naifId: -98,
		launchDate: '2006-01-19',
		color: 0xaa44ff,
		description: 'First reconnaissance of Pluto and the Kuiper Belt (Arrokoth flyby 2019)',
		status: 'active',
	},
];
